---
- hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  vars:
    compose_directory: /data/damocles.minetest.land
  tasks:
    - name: Git checkout
      git:
        repo: "git@github.com:damocles-minetest/damocles.minetest.land.git"
        dest: "{{ compose_directory }}"
        version: "{{ lookup('env', 'GITHUB_SHA') }}"

    - name: Create and start services
      community.general.docker_compose:
        project_src: "{{ compose_directory }}"
        pull: yes
        remove_orphans: yes
      register: output
