version: "2"

services:
 minetest:
  image: registry.rudin.io/x86/minetest:pandorabox
  restart: always
  ports:
   - "30002:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest:/data"
   - "./data/minetest/debug.txt:/root/.minetest/debug.txt"
  working_dir: /data
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet
  logging:
   options:
    max-size: 50m

 postgres:
  image: postgres:10
  restart: always
  shm_size: '2gb'
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres-minetest:/var/lib/postgresql/data"
  logging:
   options:
    max-size: 50m

 mapserver:
  image: registry.rudin.io/x86/mapserver
  restart: always
  networks:
   - default
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest/world:/minetest"
  working_dir: "/minetest"
  logging:
   options:
    max-size: 50m

 nginx:
  image: nginx
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - mapserver
  environment:
   VIRTUAL_PORT: 80
   VIRTUAL_HOST: damocles.minetest.land
   LETSENCRYPT_HOST: damocles.minetest.land
   LETSENCRYPT_EMAIL: thomas@rudin.io
  volumes:
   - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./data/nginx/routes:/routes"
   - "./data/nginx/html:/html"
  logging:
   options:
    max-size: 50m

networks:
 terminator:
  external: true

 
