version: "2.1"

services:
 damocles-minetest:
  image: buckaroobanzay/minetest:5.4.0-r2
  restart: always
  networks:
   - terminator
   - default
  ports:
   - "30002:30002/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest:/data"
   - "./data/minetest/debug.txt:/root/.minetest/debug.txt"
  working_dir: /data
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet
  logging:
   options:
    max-size: 50m

 postgres:
  image: postgres:12.6
  restart: always
  shm_size: '2gb'
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres:/var/lib/postgresql/data"
  logging:
   options:
    max-size: 50m

 auth-proxy:
  image: minetestauth/minetest-auth-proxy:1.2
  restart: always

 wiki:
  image: buckaroobanzay/php
  restart: always
  depends_on:
   - "postgres"
   - "auth-proxy"
  volumes:
   - "./data/wiki/extensions:/var/www/html/extensions"
   - "./data/wiki/images:/var/www/html/images"
   - "./data/wiki/LocalSettings.php:/var/www/html/LocalSettings.php"

  logging:
   options:
    max-size: 50m

 mapserver:
  image: minetestmapserver/mapserver:4.3
  restart: always
  networks:
   - default
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest/world:/minetest"
  working_dir: "/minetest"
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  logging:
   options:
    max-size: 50m

 beerchat-proxy:
  image: beerchat/beerchat:1.1
  restart: always
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  volumes:
   - "./data/beerchat.js:/data/beerchat.js:ro"

 webmail:
  image: minetestmail/mail:1.2
  restart: always
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  depends_on:
   - damocles-minetest

 manager:
  image: buckaroobanzay/minetest_manager
  restart: always
  volumes:
   - "./data:/data"
  environment:
   - WORLDMODS_DIR=/data/minetest/world/worldmods
   - WORLDMODS_BRANCH=master
   - MEDIADIR=/data/nginx/html/media
   - DEBUG_LOG=/data/minetest/debug.txt
   - ERROR_LOG_OUTPUT=/data/nginx/html/error-log.txt
  logging:
   options:
    max-size: 50m

 nodered:
  image: nodered/node-red:2.1.0-12-minimal
  restart: always
  environment:
  - TZ=Europe/Zurich
  volumes:
   - "./data/nodered:/data"
   - "./data/minetest/world:/minetest"
  logging:
   options:
    max-size: 50m

 nginx:
  image: nginx:1.21.3
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - damocles-minetest
   - mapserver
   - wiki
   - webmail
   - nodered
  environment:
   VIRTUAL_PORT: 80
   VIRTUAL_HOST: damocles.minetest.land
   LETSENCRYPT_HOST: damocles.minetest.land
   LETSENCRYPT_EMAIL: thomas@rudin.io
  labels:
    - "traefik.enable=true"
    - "traefik.docker.network=terminator"
    - "traefik.http.routers.damocles.rule=Host(`damocles.minetest.land`)"
    - "traefik.http.services.damocles.loadbalancer.server.port=80"
    - "traefik.http.routers.damocles.entrypoints=websecure"
    - "traefik.http.routers.damocles.tls.certresolver=default"
  volumes:
   - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./data/nginx/htpasswd:/etc/nginx/htpasswd:ro"
   - "./data/nginx/routes:/routes"
   - "./data/nginx/html:/html"
  logging:
   options:
    max-size: 50m

networks:
 terminator:
  external: true
