version: "2"

services:
 minetest:
  image: buckaroobanzay/minetest:pandorabox
  restart: always
  ports:
   - "30002:30002/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest:/data"
   - "./data/minetest/debug.txt:/root/.minetest/debug.txt"
  working_dir: /data
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet
  logging:
   options:
    max-size: 50m

 postgres:
  image: postgres:11
  restart: always
  shm_size: '2gb'
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres:/var/lib/postgresql/data"
  logging:
   options:
    max-size: 50m

 auth-proxy:
  image: minetestauth/minetest-auth-proxy
  restart: always

 wiki:
  image: buckaroobanzay/php
  restart: always
  depends_on:
   - "postgres"
   - "auth-proxy"
  volumes:
   - "./data/wiki:/var/www/html"
  logging:
   options:
    max-size: 50m

 mapserver:
  image: minetestmapserver/mapserver:latest
  restart: always
  networks:
   - default
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest/world:/minetest"
  working_dir: "/minetest"
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  logging:
   options:
    max-size: 50m

 highscore:
  image: registry.rudin.io/x86/minetest-xp-highscore
  restart: always
  volumes:
   - "./data/minetest/world:/data/world:ro"
  depends_on:
   - postgres
  environment:
   PGHOST: postgres
   PGUSER: postgres
   PGDATABASE: minetest
   PGPASSWORD: enter
   PGPORT: 5432

 beerchat-proxy:
  image: beerchat/beerchat
  restart: always
  volumes:
   - "./data/beerchat.json:/data/beerchat.json:ro"

 webmail:
  image: minetestmail/mail
  restart: always
  depends_on:
   - minetest

 schembrowser:
  image: filebrowser/filebrowser
  volumes:
   - "./data/minetest/world/schems:/srv"
   - "./data/schembrowser.db:/database.db"
   - "./data/schembrowser.json:/.filebrowser.json"

 worldmodupdater:
  image: alpine/git
  restart: always
  volumes:
   - "./:/project"
   - "/root/.ssh:/root/.ssh"
  entrypoint: "/project/jobs/update-worldmods.sh"
  logging:
   options:
    max-size: 50m

 nginx:
  image: nginx
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - mapserver
   - wiki
   - webmail
   - highscore
   - schembrowser
  environment:
   VIRTUAL_PORT: 80
   VIRTUAL_HOST: damocles.minetest.land
   LETSENCRYPT_HOST: damocles.minetest.land
   LETSENCRYPT_EMAIL: thomas@rudin.io
  volumes:
   - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./data/nginx/routes:/routes"
   - "./data/nginx/html:/html"
  logging:
   options:
    max-size: 50m

networks:
 terminator:
  external: true

 
