version: "2"

services:
 minetest:
  image: registry.rudin.io/x86/minetest:5.1.0-pandora
  restart: always
  ports:
   - "30002:30000/udp"
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest:/data"
   - "./data/minetest/debug.txt:/root/.minetest/debug.txt"
  working_dir: /data
  command: minetestserver --config /data/minetest.conf --world /data/world/ --quiet
  logging:
   options:
    max-size: 50m

 postgres:
  image: postgres:11
  restart: always
  shm_size: '2gb'
  environment:
   POSTGRES_PASSWORD: enter
  volumes:
   - "./data/postgres:/var/lib/postgresql/data"
  logging:
   options:
    max-size: 50m

 auth-proxy:
  image: registry.rudin.io/x86/mt-auth-proxy:latest
  restart: always

 wiki:
  image: registry.rudin.io/x86/php-pandorabox
  restart: always
  depends_on:
   - "postgres"
   - "auth-proxy"
  volumes:
   - "./data/wiki:/var/www/html"
  logging:
   options:
    max-size: 50m

 mapserver:
  image: registry.rudin.io/x86/mapserver
  restart: always
  networks:
   - default
  depends_on:
   - "postgres"
  volumes:
   - "./data/minetest/world:/minetest"
  working_dir: "/minetest"
  labels:
   com.centurylinklabs.watchtower.enable: "true"
  logging:
   options:
    max-size: 50m

 highscore:
  image: registry.rudin.io/x86/minetest-xp-highscore
  restart: always
  volumes:
   - "./data/minetest/world:/data/world:ro"
  depends_on:
   - postgres
  environment:
   PGHOST: postgres
   PGUSER: postgres
   PGDATABASE: minetest
   PGPASSWORD: enter
   PGPORT: 5432

 beerchat-proxy:
  image: registry.rudin.io/x86/beerchat_proxy:latest
  restart: always
  environment:
   IRC_HOST: chat.freenode.net
   IRC_CHANNEL: damocles
   IRC_USERNAME: damoclesbot

 webmail:
  image: registry.rudin.io/x86/minetest-webmail
  restart: always
  depends_on:
   - minetest


 nginx:
  image: nginx
  networks:
   - terminator
   - default
  restart: always
  depends_on:
   - mapserver
   - wiki
   - webmail
   - highscore
  environment:
   VIRTUAL_PORT: 80
   VIRTUAL_HOST: damocles.minetest.land
   LETSENCRYPT_HOST: damocles.minetest.land
   LETSENCRYPT_EMAIL: thomas@rudin.io
  volumes:
   - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
   - "./data/nginx/routes:/routes"
   - "./data/nginx/html:/html"
  logging:
   options:
    max-size: 50m

networks:
 terminator:
  external: true

 
