name: deployment

on:
  repository_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install deps
      run: |
        sudo apt-get install ansible
        sudo ansible-galaxy collection install community.general

    - name: update deployment
      run: |
        # validate config
        docker-compose config -q
        # set up ssh
        eval $(ssh-agent -s)
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' | ssh-add -
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        touch ~/.ssh/known_hosts
        chmod 644 ~/.ssh/known_hosts
        ssh-keyscan pandorabox.io >> ~/.ssh/known_hosts
        ansible-playbook -i damocles.minetest.land, deploy.yml
