name: docker-compose-validate

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: validate config
      run: docker-compose config -q
